### ISSUE TITLE
Click keyword in app-db tab to add path

### ISSUE THREAD

**Issue by Dexterminator** [day8/re-frame-10x#117]
I find myself expanding the app-db structure, and then typing paths over and over into the `[:path :into :app-db]` input in order to "zoom in" more and more.

Perhaps it would be convenient to be able to click a key in a data browser in order to have the full path added to the list of sub-paths in the app-db tab, e.g:

Click `:baz` in...
```clojure
{:foo {:bar {:baz "quux"}}
 :foo2 {}}
```
...and get `[:foo :bar :baz]` added to the list of sub-paths.

**Comment by danielcompton** [comment]
This is a lot harder than you might first think, as I don't have the 'path' through the data structure at any point when I'm rendering the JSONML returned by cljs-devtools. This also shows up in the app-db expansions not being particularly stable when large changes happen to the data being rendered, due to them being based on the path through the HTML, rather than the path through the data.

I think probably what is necessary is to make a patch to cljs-devtools to add the current path through the data structure as extra config data on the object, so I can pull it out when rendering.

**Comment by mike-thompson-day8** [comment]
I've asked:  https://github.com/binaryage/cljs-devtools/issues/56
