### ISSUE TITLE
Move away from slurping files at compile time

### ISSUE THREAD

**Issue by danielcompton** [day8/re-frame-10x#171]
With the new ClojureScript AOT cache, we should try and find different ways of doing https://github.com/Day8/re-frame-10x/blob/master/src/day8/re_frame_10x/utils/macros.clj#L5-L15. While it's not user configurable, so won't vary between compiles, it seems like it would be better if possible to take a different approach.

**Comment by superstructor** [comment]
This used to be used to read `*.svg` files from disk then insert those files as image data uris into the markup.

We now take a different approach where svgs are Clojure hiccup (i.e. just a reagent view) that is rendered embedded into the markup as svg elements instead of a data uri. 

So this issue is resolved.
