### ISSUE TITLE
Add ability to Search, Sort, and/or Pin subscriptions

### ISSUE THREAD

**Issue by SVMBrown** [day8/re-frame-10x#176]
Currently, it is difficult to find a particular subscription in the "Subs" tab. It would be nice to have a search bar similar to the path inspector in the "app-db" tab. Alternatively, it would be nice to be able to pin several subscriptions to the top of the list of subscriptions.

**Comment by danielcompton** [comment]
We've had similar thoughts about this too. Only showing the subscriptions that run in an epoch helps, but if you have a lot I can see how it might still be a bit tricky. We don't really have any time budget left at the moment to work on this, but could be interested in a PR, though if anyone wants to provide one, discuss it first before going through tons of work.

**Comment by SVMBrown** [comment]
I hacked together a first attempt, but it's not quite complete. I added an intermediate subscription between `:subs/all-subs` and `:subs/visible-subs` called `:subs/sorted-subs` that, for now, just filters out pinned subs and puts them at the front of the list. I am happy to do some more work on this, just let me know how you see these features fitting into the UX. my fork: https://github.com/SVMBrown/re-frame-10x/tree/pin-subs

**Comment by shen-tian** [comment]
I've got some time to work on this. Thoughts:

- Make sense to sort by name of subscription by default? There's doesn't seem to be another convenient natural sort order.
- Allow a search bar to narrow down, based on what's being displayed
- A way to pin a few to the top, assuming they are run. Something similar to @SVMBrown 's spike

That make sense?

**Comment by kimo-k** [comment]
https://github.com/day8/re-frame-10x/commit/ce234c84294316185d2b5d458e45de007926c4f1

**Comment by kimo-k** [comment]
ce234c84294316185d2b5d458e45de007926c4f1 enables search & pin for all users. 

Sorting precedence is by pinned (true/false), then by subscription path (alphabetic).

I could imagine more UX for sorting. For instance, clickable column headers. The option to sort by activity type, layer, or even new columns like timing, might be nice.

Closing for now, since this advanced sorting isn't mentioned by @SVMBrown. If anyone wants this, feel free to open a new ticket :)
