### ISSUE TITLE
Investigate using `:npm-deps` to specify dependencies for Shadow CLJS users

### ISSUE THREAD

**Issue by danielcompton** [day8/re-frame-10x#188]
https://github.com/Day8/re-frame-10x/pull/180#issuecomment-378608979

> Don't know how you feel about adding the npm deps to :npm-deps in a deps.cljs for re-frame-10x so they don't have to be added manually. I believe however this messes with standard CLJS when still using CLJSJS.

We should look into how this works and what we can do to make things easier for Shadow users.

**Comment by Deraen** [comment]
No need to use `:npm-deps` here.

If the Cljsjs packages used here (react-filp-move and react-highlight) are updated to use `:global-exports`, and provide npm-style names, they can be required in the same manner as Cljs namespaces or Node modules:

`(:require [react-flip-move :as react-flip-move])`

The the same code will work with Cljsjs packages, ClojureScript compiler with Node modules and with Shadow-cljs. 

E.g create-react-class provides simple example of Cljsjs package which uses global-exports and provides the npm-style name: https://github.com/cljsjs/packages/blob/master/create-react-class/build.boot#L25-L27 (and for backwards comptilibity it also provides the old-style cljsjs.* name). Cljsjs wiki provides some more information on this: https://github.com/cljsjs/packages/wiki/Unified-module-names-and-global-exports

Reagent 0.8.0 already uses this to access React, so that will work with all environments.

**Comment by danielcompton** [comment]
Is there more required to properly fix this?

**Comment by talgiat** [comment]
We are using shadow-cljs with newer react versions and when you build the project with shadow it tries to npm install the versions in re-frame-10x deps.cljs. I couldn't find a way to prevent that, because shadow does not use the :install-deps compiler option (at least according to the docs)

**Comment by superstructor** [comment]
@talgiat Thanks for reporting. This has been fixed on `master` and will be part of the next release.
