### ISSUE TITLE
React.createElement: type is invalid with shadow-cljs and storybook

### ISSUE THREAD

**Issue by colindresj** [Day8/re-frame-10x#195]
When running React storybook via a shadow-cljs build, I'm running into rendering errors. Following up on a conversation I had with @danielcompton on Slack yesterday, here's a repro case: https://github.com/colindresj/re-frame-10x-shadow-repro

**Comment by danielcompton** [comment]
I took a look at this, can you update it to include a component that will work and show up in a storybook when re-frame-10x is excluded? Just so I know what a fully working example should look like? It's not clear from the error whether the issue is re-com or 10x.

Also, I noted that when I include the `re-com` dependency in shadow-cljs, I get a bunch of warnings from shadow-cljs about cljs-time namespaces not existing.

**Comment by colindresj** [comment]
Updated the repro case with working plain Reagent component and re-com component @danielcompton. 

I am also getting the cljs-time warnings when requiring re-com, but doesn't seem to be causing any issues with my example. Might be an issue if using the datepicker. Looping in @thheller in case he has some input re: cljs-time warnings.

**Comment by thheller** [comment]
`cljs-time` warnings are due to an old version which doesn't have this fix: https://github.com/andrewmcveigh/cljs-time/commit/728e6cb151813194dc32de2a229833f08bcc5dde.

`[com.andrewmcveigh/cljs-time "0.5.2"]` works properly.

Not a clue about the other stuff.

**Comment by colindresj** [comment]
Yep, I updated the dependencies to include version 0.5.2 of cljs-time (while excluding from re-com) and warnings go away. Thanks, @thheller.

**Comment by danielcompton** [comment]
Not sure if this is related or not, but I see this in the code in a few places: `shadow.js.shim.module$react.createElement(comp,jsprops);`. I updated to `"0.3.3-react16"` and was able to make it work by doing this:

```
(ns repro.stories.core
  (:require
    ;[day8.re-frame-10x.preload]
    [day8.re-frame-10x :as trace]
            [re-frame.trace :refer [trace-enabled?]]
            [reagent.core :as r]
            ["@storybook/react" :refer [storiesOf]]
            [repro.stories.counter :refer [counter re-com-counter]]))

(trace/init-db!)
(defonce _ (trace/init-tracing!))

(.log js/console "goog.DEBUG:" goog.DEBUG)
(.log js/console "re-frame.trace/trace-enabled?" trace-enabled?)

(-> (storiesOf "A counter written in CLJS" js/module)
    (.add "Plain reagent" #(r/as-element [counter]))
    (.add "With mranders re-com" #(r/as-element [re-com-counter])))

(js/setTimeout #(trace/inject-devtools!)
               500)
```

There is something about injecting devtools later which makes it work. I don't really know what the issue is, and there are lots of technologies involved here. I'm happy to take a PR, but I'm not sure if I'm going to be able to take this much further at the moment.

**Comment by thheller** [comment]
`shadow.js.shim.module$react` is the alias namespace created by shadow-cljs when requiring the npm `react` package. It is just `shadow.js.shim.module$react = require("react");` basically. It is the alias created when requiring `react` via the `ns` (as `reagent` 0.8.0 does).

**Comment by colindresj** [comment]
After a bit more digging, I managed to track down the issue. Turns out the latest version of react-flip-move default exports, so updating `js/FlipMove` to `js/FlipMove.default` in `day8.re-frame-10x.utils.animated` fixed my issue. 

This shouldn't be a problem for most people, but since I'm not using `cljsjs` it turned out to be one for my specific use case. Don't think there's anything to change in re-frame-10x, and adding a `cljsjs.react-flip-move` namespace where I require `:default` via shadow and export the symbol works fine enough for me.

Going to go ahead and close this.

**Comment by danielcompton** [comment]
Whew, thanks for digging into this, that must have been tricky to debug!

**Comment by colindresj** [comment]
No problem, good to know it's all working. So many different techs working together -- kind of amazing how it works once the initial kinks are ironed out.

I did notice a little problem that is most noticeable in shadow-cljs, so will open up a small PR to address.
