### ISSUE TITLE
10x content not visible until pop-out

### ISSUE THREAD

**Issue by maikelvallinga** [day8/re-frame-10x#264]
When i open the 10x window it does not show any content except buttons. So i am not able to see the app-db for example.

When i pop out the screen the content is displaying correctly and i can see the app-db. Problem occurs within Safari and Chrome.

Example with just the 10x window open:
![Screenshot 2020-05-19 at 10 30 02](https://user-images.githubusercontent.com/13588463/82303938-f1082b80-99bb-11ea-86bc-5b341be37418.png)

Example when i pop out the window:
![Screenshot 2020-05-19 at 10 30 21](https://user-images.githubusercontent.com/13588463/82304002-07ae8280-99bc-11ea-94d3-52c1c23765d7.png)

**Comment by whmountains** [comment]
I have a similar problem.  My app dispatches `:initialize-db` on startup, but that is not shown in re-frame until I pop out.  Then it suddenly appears.

**Comment by superstructor** [comment]
I cannot reproduce this issue in the example todomvc app, although the last comment on not rendering the first event on startup sounds suspiciously similar to #263

**Comment by bpringe** [comment]
This is happening to me as well. I tried in Chrome and Brave (Chromium based).

**Comment by superstructor** [comment]
@MawiraIke are you able to reproduce ?

**Comment by MawiraIke** [comment]
Yes @superstructor I can reproduce this issue in a new repo with only the `initialize-db` event. For example, I can reproduce it when I create a new re-frame project with `lein new re-frame` and add `re-com` and `10x`. I also can't reproduce the issue in the todomvc app as you mentioned.
Fair to note that @bpringe solution fixes this problem. That is using `dispatch` instead of `dispatch-sync` shows the events and db when the page loads. I think this delay might be related to `dispatch-sync`. Hovering the mouse on some components (like the v-box drag-bar for example) also seems to make the db catch up with the latest event.

**Comment by kimo-k** [comment]
`dispatch-sync` problem is solved for #263 and #151.

I'm running the repro on the same lein template, but I don't see the original behavior reported by @maikelvallinga regarding the popout window. Looking at the code, there's nothing explicitly happening with the popout window to start or stop trace.

A problem does remain, but it's more of a feature, I think: trace doesn't run unless the panel is open.

I've added a new setting to control this. Now, you can choose for 10x to trace your app:
- when the panel is open (default)
- always (even when the panel is closed. when you do open it, all the trace will be there.)
- never (immediately kills all trace)
