### ISSUE TITLE
Events that return app-db unchanged seem to cause the event history to lag

### ISSUE THREAD

**Issue by stumitchell** [day8/re-frame-10x#268]
We created a situation where the Event Tab was showing trace for the "Last event", not the "current event". There was a one-event lag. 

An event handler written with an implied `do` seems to be the cause. Eg: 

```clj
(re-frame/reg-event-db
 :event
 (fn-traced [db _]
   (let [a 10                               ;; <-- implied do with two forms  (see db below)
         b (+ a 20)]
     (+ a b))
   db)))
```

**Comment by jtlocsei** [comment]
This might be unrelated, but could it be that you didn't yet have a subscription that uses the data that's updated in the db by the event? It seems like the refresh of re-frame-10x display is triggered by data flow in a subscription. I had was seeing a one-event-lag and it was fixed when I added the subscription. Jacek Schae talks about the issue briefly at the end of Video 8 in his free re-frame course https://www.jacekschae.com/learn-re-frame-free (no affiliation)

**Comment by superstructor** [comment]
@MawiraIke Have a look at this please.

**Comment by MawiraIke** [comment]
I can reproduce this issue in the latest re-frame-10x version (1.2.7) although it's somehow different now. Using the todos app, there is a delay in showing the trace for the latest event, i.e 

```Clojure
(re-frame/reg-event-db
 :event
 (fn-traced [db _]
   (let [a 10                               ;; <-- implied do with two forms  (see db below)
         b (+ a 20)]
     (+ a b))
   db)))
```

although the delay ends after clicking any part of the window. Afterwards, the event tab updates to show the most recent trace.

**Comment by kimo-k** [comment]
Hey @stumitchell, interesting case. I don't think this is caused by the implicit `do`, though.
Rather, this behavior arises when the new app-db is identical to the old one.

This doesn't work:
```clojure
(reg-event-db :bad-event (fn [db _] db))
 ```
 While this does:
 ```clojure
(reg-event-db :good-event (fn [db _] (assoc db ::gensym (gensym))))
 ```
 
We accumulate trace at various sites, but we only once do we express a [quiescent trace](https://github.com/day8/re-frame-10x/blob/cbd0fde969db2f6feb79070da7e01c84d37d6e0d/src/day8/reagent/impl/batching.cljs#L20). Reagent's render queue should invoke this in its final loop as it handles a reset of the app-db. The problem is, [there is no reset](https://github.com/day8/re-frame-10x/blob/cbd0fde969db2f6feb79070da7e01c84d37d6e0d/gen-src/day8/re_frame_10x/inlined_deps/re_frame/v1v1v2/re_frame/fx.cljc#L184). Nothing is scheduled, no quiescence.

Without quiescence, there is no [match](https://github.com/day8/re-frame-10x/blob/cbd0fde969db2f6feb79070da7e01c84d37d6e0d/src/day8/re_frame_10x/tools/metamorphic.cljc#L234) until [the next epoch begins](https://github.com/day8/re-frame-10x/blob/cbd0fde969db2f6feb79070da7e01c84d37d6e0d/src/day8/re_frame_10x/tools/metamorphic.cljc#L242). In other words, 10x batches the epoch, thinking there are more soon to come.

I think this is a complete picture, but I'm still not sure what to do about it. I made a [test branch](https://github.com/day8/re-frame-10x/tree/db-noop-event), which makes all events return a new app-db. This may be intrusive for the user, though, and it seems inelegant.

**Comment by kimo-k** [comment]
I found an obvious solution based on the above analysis. The effect of an unchanged db is a new moment of quiescence, and it's straightforward to trace this moment.
