### ISSUE TITLE
Add a v-split between Event History panel and the tabs panel below

### ISSUE THREAD

**Issue by Gregg8** [day8/re-frame-10x#311]
Sometimes you need as much vertical space as you can get for viewing the **path inspectors** or the **subs** lists. In this case you don't want any space taken up by the **Event History** window.

But if you need to focus on events, there is currently only a small amount of vertical space to view those. This is made more impractical if you want to view the event data.

A `v-split` component between the two would solve these problems.

Optional: Given how much time rendering complex data structures can affect the performance of the app you're debugging, it would also be useful to have a `checkbox` which hides/shows the **Event History** panel.

**Comment by MawiraIke** [comment]
@superstructor this issue needs manual copying of `re-com.core/v-split` to `re-frame-10x` or finalization of component restyling in [re-com](https://github.com/day8/re-com/issues/284). Should I proceed to copy the `v-split` (which will be overwritten later) or wait for those changes?
I have added a toggle checkbox to show or hide the event history as suggested which leaves maximum space for `app-db`, `subs` etc when the event history is hidden.

**Comment by superstructor** [comment]
@MawiraIke please copy v-split to the inline copy of re-com included with re-frame-10x. As you well know, its not 'real' re-com, so make appropriate adjustments. In other words, I doubt it can be copied verbatim. Also, 10x has self-contained styles independent of the app/page (because real re-com could be running on the user's app). So you can't use the re-com styles, those need to be re-written to be contained ala the other existing components in 10x.
