### ISSUE TITLE
Scrolling problem in the Event History panel

### ISSUE THREAD

**Issue by Gregg8** [day8/re-frame-10x#312]
When you select an event in the **Event History** panel, 10x will continuously scroll back to that event, which prevents you from scrolling to other events to view them.

In fact, the scrolling back only seems to happen when you've expanded the data for that event.

**Comment by Gregg8** [comment]
This might be good to add to: https://github.com/day8/re-frame-10x/issues/302

**Comment by MawiraIke** [comment]
This issue is caused by triggering of [componentDidUpdate](https://github.com/day8/re-frame-10x/blob/1.4.1/src/day8/re_frame_10x/navigation/epochs/views.cljs#L45) in the lifecycle of selected epochs. I have been able to reproduce the issue when leaving mouse hover on a selected epoch. It seems that [componentDidUpdate](https://github.com/day8/re-frame-10x/blob/1.4.1/src/day8/re_frame_10x/navigation/epochs/views.cljs#L45) is triggered every time the mouse [hovers](https://github.com/day8/re-frame-10x/blob/master/src/day8/re_frame_10x/navigation/epochs/views.cljs#L60) (or [leaves mouse hover](https://github.com/day8/re-frame-10x/blob/master/src/day8/re_frame_10x/navigation/epochs/views.cljs#L61)) on a selected epoch. I think this is because we are tracking the current hovered epoch and updating the style of epochs depending on the mouse hover. This then updates the DOM and indirectly triggers the componentDidUpdate method. So every time a user moves the mouse from the selected epoch to another NOT selected epoch, we indirectly call [componentDidUpdate](https://github.com/day8/re-frame-10x/blob/1.4.1/src/day8/re_frame_10x/navigation/epochs/views.cljs#L45) and cause the DOM to scroll to the selected epoch again. 
@superstructor my suggestion is to stop listening to [componentDidUpdate](https://github.com/day8/re-frame-10x/blob/1.4.1/src/day8/re_frame_10x/navigation/epochs/views.cljs#L45) unless there was another intention of the callback that I have not discovered. Removing the callback seems to fix the issue.

**Comment by superstructor** [comment]
Ok thanks @MawiraIke I've reviewed the linked code and agree yes please stop listing to componentDidUpdate.
