### ISSUE TITLE
[Enhancement]: 1.2.0 "copy object" should allow non object elements to be copied

### ISSUE THREAD

**Issue by hipitihop** [day8/re-frame-10x#329]
### What do you suggest?

In 1.2.0 "copy object" is a most welcome addition, however it causes a console error "copy object failed" or similar when used on simple elements/values like strings.

**Comment by MawiraIke** [comment]
@hipitihop I have managed to reproduce this and I am working to fix it. In the meantime, it seems that typing in the input box to narrow down on a child and then trying to use "copy object" afterwards works. Even after clearing the input box.

**Comment by MawiraIke** [comment]
After some dive into this, this issue seems to occur specifically when some application state is added after the `app-db` rendering has been done. After rendering, "copy object" seems to fail to work on the newly added data. 
For example after a page loads and the re-frame-10x panel is currently watching another tab (like `traces`, `event`, `fx` etc) and then you switch to `app-db`, everything seems to work as intended.

**Comment by MawiraIke** [comment]
I have added a commit #333 that should fix this issue. 
Thank you for spotting it.
